#!/usr/bin/env python3
"""Decompose an axis-aligned building mesh into MuJoCo collision boxes (an MJCF include).

Usage: mesh_to_walls.py worlds/meshes/uni-bremen_secoro.stl worlds/secoro_walls.xml
"""

import argparse
import pathlib

import mujoco
import numpy as np

# skewed off the axes so the parity ray misses edges and vertices of axis-aligned faces
RAY = np.array([1.0, 0.0123, 0.0071])
WALL_RGBA = '0.85 0.85 0.8 1'
# geom groups shared with worlds/*.xml (building mesh 1) and eddie_driver_node's top view
WALL_GROUP = 3
LINTEL_GROUP = 4


def load(stl):
    model = mujoco.MjModel.from_xml_string(
        f'<mujoco><asset><mesh name="m" file="{stl.resolve()}"/></asset>'
        '<worldbody><geom type="mesh" mesh="m"/></worldbody></mujoco>')
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    verts = data.geom_xpos[0] + model.mesh_vert[:model.mesh_vertnum[0]] @ data.geom_xmat[
        0].reshape(3, 3).T
    return verts, model.mesh_face[:model.mesh_facenum[0]]


def components(faces, nvert):
    parent = list(range(nvert))

    def root(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for a, b, c in faces:
        parent[root(b)] = root(a)
        parent[root(c)] = root(a)
    groups = {}
    for t, f in enumerate(faces):
        groups.setdefault(root(f[0]), []).append(t)
    return [faces[t] for t in groups.values()]


def inside(tris, p):
    e1 = tris[:, 1] - tris[:, 0]
    e2 = tris[:, 2] - tris[:, 0]
    h = np.cross(RAY, e2)
    a = np.einsum('ij,ij->i', e1, h)
    ok = np.abs(a) > 1e-12
    f = 1.0 / np.where(ok, a, 1.0)
    s = p - tris[:, 0]
    u = f * np.einsum('ij,ij->i', s, h)
    q = np.cross(s, e1)
    v = f * (q @ RAY)
    t = f * np.einsum('ij,ij->i', e2, q)
    return np.count_nonzero(ok & (u >= 0) & (v >= 0) & (u + v <= 1) & (t > 0)) % 2 == 1


def merge(filled):
    left = filled.copy()
    out = []
    for i, j, k in zip(*np.nonzero(filled)):
        if not left[i, j, k]:
            continue
        i1 = i + 1
        while i1 < left.shape[0] and left[i1, j, k]:
            i1 += 1
        j1 = j + 1
        while j1 < left.shape[1] and left[i:i1, j1, k].all():
            j1 += 1
        k1 = k + 1
        while k1 < left.shape[2] and left[i:i1, j:j1, k1].all():
            k1 += 1
        left[i:i1, j:j1, k:k1] = False
        out.append((i, i1, j, j1, k, k1))
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('stl', type=pathlib.Path)
    parser.add_argument('out', type=pathlib.Path)
    args = parser.parse_args()

    verts, faces = load(args.stl)
    tris = verts[faces]
    normals = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    if not np.allclose(np.abs(normals).max(1), np.linalg.norm(normals, axis=1), atol=1e-6):
        raise SystemExit(f'{args.stl}: not all faces are axis-aligned')

    geoms = []
    for part in components(faces, len(verts)):
        ptris = verts[part]
        # 0.1 mm: exported IFC geometry repeats a coordinate with float noise
        axes = [np.unique(np.round(ptris[..., d].ravel(), 4)) for d in range(3)]
        mids = [(c[:-1] + c[1:]) / 2 for c in axes]
        filled = np.zeros([len(m) for m in mids], dtype=bool)
        for idx in np.ndindex(filled.shape):
            filled[idx] = inside(ptris, np.array([mids[d][idx[d]] for d in range(3)]))
        for i, i1, j, j1, k, k1 in merge(filled):
            lo = np.array([axes[0][i], axes[1][j], axes[2][k]])
            hi = np.array([axes[0][i1], axes[1][j1], axes[2][k1]])
            pos = ' '.join(f'{x:.4f}' for x in (lo + hi) / 2)
            size = ' '.join(f'{x:.4f}' for x in (hi - lo) / 2)
            # the top view hides lintels to show the doorways
            group = LINTEL_GROUP if lo[2] > 1e-3 else WALL_GROUP
            geoms.append(f'  <geom type="box" pos="{pos}" size="{size}" group="{group}" '
                         f'rgba="{WALL_RGBA}"/>')

    args.out.write_text(
        f'<!-- generated by scripts/mesh_to_walls.py from {args.stl.name}, in its frame -->\n'
        '<mujoco>\n' + '\n'.join(geoms) + '\n</mujoco>\n')
    print(f'{args.out}: {len(geoms)} boxes')


if __name__ == '__main__':
    main()
